# 应用服务 WEB 访问端口
server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://150.158.98.221:3307/hospital
    username: root
    password: ENC(49sIrimhHZuhLd6jPwYAZq3mc1nj0E1X)
    type: com.alibaba.druid.pool.DruidDataSource

jasypt:
  encryptor:
    password: Angel
    algorithm: PBEWithMD5AndDES

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.qin.hospital.entity